//
//  QuotesController.swift
//  MySoberDate
//
//  Created by Wylan L Neely on 3/2/24.
//

import Foundation
import UIKit


struct Quotes {
    
    let quotes = [
        quote1, quote2, quote3, quote4, quote5,quote71, quote6, quote7, quote8, quote9, quote10,quote11, quote75,quote12, quote13, quote14, quote15, quote16, quote17, quote18, quote19, quote20,quote21, quote22, quote23, quote24,quote74,quote25, quote26, quote27, quote28, quote29, quote30,quote31, quote32, quote33, quote34, quote35, quote36, quote37, quote38, quote39, quote40,quote41, quote42, quote43, quote44, quote45, quote46, quote47,quote72,quote48, quote49, quote50,quote51,quote52,quote77,quote53, quote54, quote55,quote73, quote56, quote57,quote59,quote60,quote61,quote62,quote63,quote64,quote65,quote66,quote67,quote68,quote69,quote70,quote78,quote79,quote80,quote81,quote82,quote83,quote84,quote85,quote86,quote87,quote88,quote89,quote90,quote76, quote91, quote92, quote93, quote94, quote95, quote96, quote97, quote98, quote99, quote100, quote101, quote102, quote103, quote104, quote105, quote106, quote107, quote108, quote109, quote110, quote111, quote112, quote113, quote114, quote115, quote116, quote117, quote118, quote119, quote120, quote121, quote122, quote123, quote124, quote125, quote126, quote127, quote128, quote129, quote130, quote131, quote132, quote133, quote134, quote135, quote136, quote137, quote138, quote139, quote140, quote141, quote142, quote143,quote144, quote145, quote146, quote147, quote148, quote149, quote150, quote151, quote152, quote153, quote154, quote155, quote156, quote157, quote158, quote159, quote160, quote161, quote162, quote163, quote164, quote165, quote166, quote167, quote168, quote169, quote170, quote171, quote172, quote173, quote174, quote175, quote176, quote177, quote178, quote179, quote180, quote181, quote182, quote183, quote184, quote185, quote186, quote187, quote188, quote189, quote190, quote191, quote192, quote193, quote194, quote195, quote196, quote197, quote198, quote199, quote200]


    
//    let quotes = [
//        quote1, quote2, quote3, quote4, quote5, quote6, quote7, quote8, quote9, quote10,
//        quote11, quote12, quote13, quote14, quote15, quote16, quote17, quote18, quote19, quote20,
//        quote21, quote22, quote23, quote24, quote25, quote26, quote27, quote28, quote29, quote30,
//        quote31, quote32, quote33, quote34, quote35, quote36, quote37, quote38, quote39, quote40,
//        quote41, quote42, quote43, quote44, quote45, quote46, quote47, quote48, quote49, quote50,
//        quote51, quote52, quote53, quote54, quote55, quote56, quote57, quote58, quote59, quote60,
//        quote61, quote62, quote63, quote64, quote65, quote66, quote67, quote68, quote69, quote70,
//        quote71, quote72, quote73, quote74, quote75, quote76, quote77, quote78, quote79, quote80,
//        quote81, quote82, quote83, quote84, quote85, quote86, quote87, quote88, quote89, quote90,
//        quote91, quote92, quote93, quote94, quote95, quote96, quote97, quote98, quote99, quote100
//    ]
//    
    
}


let quote1 = Quote(quote: "Sometimes you have to be a lion, so that you can be the lamb you really are.", author: "Dave Chappelle",image: UIImage(named: "dave-chappelle")!)
let quote2 = Quote(quote: "I do not like that man, I must get to know him better.", author: "Abraham Lincoln", image: UIImage(named: "abraham-lincoln")!)
let quote3 = Quote(quote: "The best and most beautiful things in the world cannot be seen or even touched... they must be felt with the heart", author: "Helen Keller", image: UIImage(named: "helen-keller")!)
let quote4 = Quote(quote: "Darkness cannot drive out darkness, only light can do that. Hate cannot drive out hate, only love can do that.", author: "Martin L. King Jr.", image: UIImage(named: "mlk")!)
let quote85 = Quote(quote: "Once you know what failure feels like, determination chases success.", author: "Kobe Bryant", image: UIImage(named: "kobe-bryant")!)
let quote6 = Quote(quote: "So you were born to feel ‘nice?’ Instead of doing things and experiencing them? Why aren’t you running to do what your nature demands?", author: "Marcus Aurelius", image: UIImage(named: "marcus-aurelius")!)
let quote17 = Quote(quote: "Do not pray for easy lives. Pray to be stronger men.", author: "Rev. Phillips Brooks", image: UIImage(named: "rev-phillips-brooks")!)
let quote8 = Quote(quote: "If freedom of speech is taken away, then dumb and silent we may be led, like sheep to the slaughter.", author: "George Washington", image: UIImage(named: "george-washington")!)
let quote9 = Quote(quote: "A new idea must not be judged by its immediate results", author: "Nikola Tesla", image: UIImage(named: "nikola-tesla")!)
let quote11 = Quote(quote:"If you want to be the best, you have to do things that other people aren't willing to do.", author: "Michael Phelps", image: UIImage(named: "michael-phelps")!)
let quote20 = Quote(quote: "No, I don't ever give up. I'd have to be dead or completely incapacitated", author: "Elon Musk", image: UIImage(named: "elon-musk")!)
let quote12 = Quote(quote: "The cynics may be the loudest voices, but I promise you, they will accomplish the least", author: "Barack Obama", image: UIImage(named: "obama")!)
let quote13 = Quote(quote: "Without passion, you don't have energy; without energy, you have nothing. Nothing great in the world has been accomplished without passion!", author: "Donald J. Trump", image: UIImage(named: "trump")!)
let quote14 = Quote(quote: "If you ever start taking things too seriously, just remember that we are talking monkeys on an organic spaceship flying through the universe.", author: "Joe Rogan", image: UIImage(named: "joe-rogan")!)
let quote15 = Quote(quote: "If I have seen further than others, it is by standing on the shoulders of Giants.", author: "Isaac Newton", image: UIImage(named: "isaac-newton")!)
let quote16 = Quote(quote: "The most difficult thing is the decision to act, the rest is merely tenacity", author: "Amelia Earhart", image: UIImage(named: "earhart")!)
let quote7 = Quote(quote: "You must never be fearful about what you are doing when it is right", author: "Rosa Parks", image: UIImage(named: "rosa-parks")!)
let quote18 = Quote(quote: "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.", author: "Harriet Tubman", image: UIImage(named: "harriet-tubman")!)
let quote190 = Quote(quote: "The most courageous act is still to think for yourself aloud.", author: "Coco Chanel", image: UIImage(named: "coco")!)
let quote10 = Quote(quote: "Humans are allergic to change. They love to say, 'We've always done it this way.' I try to fight that.", author: "Grace Hopper", image: UIImage(named: "grace-hopper")!)
let quote21 = Quote(quote: "We're here to make a dent in the universe. Otherwise, why even be here?", author: "Steve Jobs", image: UIImage(named: "jobs")!)
let quote22 = Quote(quote: "You must be the change you wish to see in the world", author: "Mahatma Gandhi", image: UIImage(named: "mahatma-gandhi")!)
let quote23 = Quote(quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", image: UIImage(named: "mother-teresa")!)
let quote24 = Quote(quote: "Keep smiling, because life is a beautiful thing and there's so much to smile about.", author: "Marilyn Monroe", image: UIImage(named: "marilyn-monroe")!)
let quote25 = Quote(quote: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison", image: UIImage(named: "thomas-edison")!)
let quote26 = Quote(quote: "I find that the harder I work, the more luck I seem to have", author: "Thomas Jefferson", image: UIImage(named: "thomas-jefferson")!)
let quote193 = Quote(quote: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Piccasso", image: UIImage(named: "pablo")!)
let quote28 = Quote(quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron", image: UIImage(named: "james-cameron")!)
let quote29 = Quote(quote: "To be successful, you have to be selfish, or else you never achieve. And once you get to your highest level, then you have to be unselfish.", author: "Michael Jordon", image: UIImage(named: "michael-jordon")!)
let quote30 = Quote(quote: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein", image: UIImage(named: "einstein")!)
let quote31 = Quote(quote: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", author: "Oprah Winfrey", image: UIImage(named: "oprah")!)
let quote32 = Quote(quote: "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.", author: "Thomas J. Watson", image: UIImage(named: "thomas-watson")!)
let quote33 = Quote(quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn", image: UIImage(named: "jim-rohn")!)
let quote34 = Quote(quote: "The question isn't who is going to let me; it's who is going to stop me", author: "Ayn Rand", image: UIImage(named: "ayn-rand")!)
let quote35 = Quote(quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", image: UIImage(named: "henry-ford")!)
let quote36 = Quote(quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", image: UIImage(named: "wayne-g")!)
let quote37 = Quote(quote: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank", image: UIImage(named: "anne-frank")!)
let quote38 = Quote(quote: "Everything you've ever wanted is on the other side of fear.", author: "George Adair", image: UIImage(named: "george-adair")!)
let quote39 = Quote(quote: "It is still best to be honest and truthful; to make the most of what we have; to be happy with simple pleasures; and have courage when things go wrong.", author: "Laura Ingalls Wilder", image: UIImage(named: "laura-wilder")!)
let quote40 = Quote(quote: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin", image: UIImage(named: "ben-franklin")!)
let quote41 = Quote(quote: "A man may die, nations may rise and fall, but an idea lives on.", author: "John F. Kennedy", image: UIImage(named: "jfk")!)
let quote42 = Quote(quote: "Nothing is impossible, the word itself says, ‘I'm possible!", author: "Audrey Hepburn", image: UIImage(named: "audrey-hepburn")!)
let quote162 = Quote(quote: "I would rather die of passion than of boredom.", author: "Vincent Van Gogh", image: UIImage(named: "gogh")!)
let quote44 = Quote(quote: "Compare yourself to who you were yesterday, not to who someone else is today.", author: "Jordan Peterson", image: UIImage(named: "jp")!)
let quote45 = Quote(quote: "You do not rise to the level of your goals, you fall to the level of your systems.", author: "James Clear", image: UIImage(named: "james-clear")!)
let quote46 = Quote(quote: "If you want to lift yourself up, lift up someone else.", author: "Brooker T. Washington", image: UIImage(named: "brooker")!)
let quote47 = Quote(quote: "The strength of the team is each individual member. The strength of each member is the team.", author: "Phil Jackson", image: UIImage(named: "phil-jackson")!)
let quote48 = Quote(quote: "Find a group of people who challenge and inspire you, spend a lot of time with them, and it will change your life.", author: "Amy Poehler", image: UIImage(named: "amy-p")!)
let quote49 = Quote(quote: "Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.", author: "Mark Twain", image: UIImage(named: "mark-twain")!)
let quote50 = Quote(quote: "Being good in business is the most fascinating kind of art. Making money is art and working is art and good business is the best art.", author: "Andy Worhol", image: UIImage(named: "andy-worhol")!)
let quote51 = Quote(quote: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine", image: UIImage(named: "j-marine")!)
let quote52 = Quote(quote: "Diamonds are nothing more than chunks of coal that stuck to their jobs.", author: "Malcom Forbes", image: UIImage(named: "forbes")!)
let quote53 = Quote(quote: "Pretend that every single person you meet has a sign around his or her neck that says, 'Make me feel important.'", author: "Mary Kay Ash", image: UIImage(named: "mary-kay")!)
let quote54 = Quote(quote: "Be poor, humble and driven (PhD). Don't be afraid to shift or pivot.", author: "Alex Rodgriguez", image: UIImage(named: "a-rod")!)
let quote55 = Quote(quote: "I'd rather regret the things I've done than regret the things I haven't done.", author: "Lucille Ball", image: UIImage(named: "l-ball")!)
let quote56 = Quote(quote: "Motivation is temporary. Inspiration is permanent.", author: "Kelly Slater", image: UIImage(named: "kelly-slater")!)
let quote57 = Quote(quote: "You gotta go in the mud sometimes to figure who you are.", author: "Andy Iorns", image: UIImage(named: "andy-irons")!)
let quote58 = Quote(quote: "Rock bottom became the solid foundation on which I rebuilt my life.", author: "J. K. Rowling", image: UIImage(named: "jk-rowling")!)
let quote59 = Quote(quote: "Hardships often prepare ordinary people for an extraordinary destiny", author: "C. S. Lewis", image: UIImage(named: "cs-lewis")!)
let quote60 = Quote(quote: "I didn't get there by wishing for it or hoping for it, but by working for it.", author: "Estée Lauder", image: UIImage(named: "estee-lauder")!)
let quote61 = Quote(quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", image: UIImage(named: "ralph-waldo")!)
let quote62 = Quote(quote: "First, you take a drink, then the drink takes a drink, then the drink takes you.", author: "F. Scott Fitzgerald", image: UIImage(named: "fscottf")!)
let quote63 = Quote(quote: "Done is better than perfect.", author: "Sheryl Sandberg", image: UIImage(named: "s-sandberg")!)
let quote64 = Quote(quote: "Remember that just because you hit bottom doesn’t mean you have to stay there.", author: "Robert Downey Jr.", image: UIImage(named: "robert-d-jr")!)
let quote65 = Quote(quote: "Don’t judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert L. Stevenson", image: UIImage(named: "robert-stevenson")!)
let quote66 = Quote(quote: "Love God; love others; do your best in all you do, even if you fall short!", author: "Bethany Hamilton", image: UIImage(named: "bethany-hamilton")!)
let quote67 = Quote(quote: "The optimist thinks this is the best of all possible worlds. The pessimist fears it is true.", author: "J. Oppenheimer", image: UIImage(named: "oppenheimer")!)
let quote68 = Quote(quote: "The most common way people give up their power is by thinking they don’t have any.", author: "Alice Walker", image: UIImage(named: "alice-walker")!)
let quote69 = Quote(quote: "One of the hardest things was learning that I was worth recovery.", author: "Demi Lovato", image: UIImage(named: "demi")!)
let quote70 = Quote(quote: "The person who goes to the gym every day regardless of how they feel, will always beat the person who only goes to the gym when they feel like it.", author: "Andrew Tate", image: UIImage(named: "andrew-tate")!)
let quote71 = Quote(quote: "Anywhere I see suffering, that is where I want to be, doing what I can.", author: "Princess Diana", image: UIImage(named: "p-diana")!)
let quote72 = Quote(quote: "Don't worry about motivation. Motivation is fickle. It comes and goes. It is unreliable - and when you are counting on motivation to get your goals accomplished, you will likely fall short.", author: "Jocko Willink", image: UIImage(named: "jocko")!)
let quote73 = Quote(quote: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius", image: UIImage(named: "confucius")!)
let quote74 = Quote(quote: "A leader leads by example not by force.", author: "Sun Tzu", image: UIImage(named: "sun-tzu")!)
let quote75 = Quote(quote: "So I say to you, Ask and it will be given to you; search, and you will find; knock, and the door will be opened for you.", author: "Jesus Christ", image: UIImage(named: "jesus")!)
let quote76 = Quote(quote: "No matter how hard the past, you can always begin again.", author: "Buddha", image: UIImage(named: "buddah")!)
let quote77 = Quote(quote: "When we meet real tragedy in life, we can react in two ways – either by losing hope and falling into self-destructive habits, or by using the challenge to find our inner strength", author: "Dalai Lama", image: UIImage(named: "dalai-lama")!)
let quote78 = Quote(quote: "I have yet to meet someone who was successful who was even slightly negative. That comes from a muscle training. You can work on negativity and weed it out of your life.", author: "Katt Williams", image: UIImage(named: "katt-w")!)
let quote79 = Quote(quote: "Anxiety is your best friend. It's there to help you. It's trying to save your life.", author: "Bill Burr", image: UIImage(named: "bill-burr")!)
let quote80 = Quote(quote: "Recognize and embrace your flaws so you can learn from them. Sometimes it takes a little polishing to truly shine.", author: "Kanye West", image: UIImage(named: "kanye")!)
let quote81 = Quote(quote: "All the suffering, stress, and addiction comes from not realizing you already are what you are looking for.", author: "Jon Kabat-Zinn", image: UIImage(named: "jon-zinn")!)
let quote82 = Quote(quote: "Ya think whiskey tastes good? Try a big cup of sobriety -- now that’s the good stuff!", author: "Steven Tyler", image: UIImage(named: "steven-tyler")!)
let quote5 = Quote(quote: "If you can quit for a day, you can quit for a lifetime.", author: "Benjamin Alire Sáenz", image: UIImage(named: "benjamin-saenz")!)
let quote84 = Quote(quote: "True ambition is not what we thought it was. True ambition is the profound desire to live usefully and walk humbly under the grace of God.", author: "Bill W.", image: UIImage(named: "bill-w")!)
let quote83 = Quote(quote: "What is addiction, really? It is a sign, a signal, a symptom of distress. It is a language that tells us about a plight that must be understood.", author: "Allice Duer Miller", image: UIImage(named: "alice-miller")!)
let quote86 = Quote(quote: "People often say that motivation doesn’t last. Neither does bathing. That’s why we recommend it daily.", author: "Zig Ziglar", image: UIImage(named: "zig-ziglar")!)
let quote87 = Quote(quote: "The greatness of a man is not in how much wealth he acquires, but in his integrity and his ability to affect those around him positively.", author: "Bob Marley", image: UIImage(named: "bob-marley")!)
let quote188 = Quote(quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", image: UIImage(named: "walt-disney")!)
let quote89 = Quote(quote: "Hitting bottom and hitting it hard was the worst thing that ever happened to me and the best thing that ever happened to me.", author: "Dave Ramsey", image: UIImage(named: "dave-r")!)
let quote90 = Quote(quote: "Addiction denied is recovery delayed.", author: "Mokokoma Mokhonoana", image: UIImage(named: "mokokoma-mokhonoana")!)
let quote91 = Quote(quote: "Though No One Can Go Back And Make A Brand New Start, Anyone Can Start From Now And Make A Brand New Ending.", author: "Carl Bard", image: UIImage(named: "carl-bard")!)
let quote92 = Quote(quote: "Sometimes We Motivate Ourselves By Thinking Of What We Want To Become. Sometimes We Motivate Ourselves By Thinking About Who We Don’t Ever Want To Be Again.", author: "Shane Niemeyer", image: UIImage(named: "shane-n")!)
let quote93 = Quote(quote: "Experience Is Not What Happens To You, It Is What You Do With What Happens To You.", author: "Aldous Huxley", image: UIImage(named: "aldous-huxley")!)
let quote94 = Quote(quote: "The opposite of addiction is not sobriety, but rather connect with others.", author: "Johann Hari", image: UIImage(named: "johann-hari")!)
let quote95 = Quote(quote: "You don’t have to see the whole staircase. Just take the first step.", author: "Martin L. King Jr.", image: UIImage(named: "mlk")!)
let quote96 = Quote(quote: "Being in recovery has given me everything of value that I have in my life. Integrity, honesty, fearlessness, faith, a relationship with God, and most of all gratitude.", author: "Rob Lowe", image: UIImage(named: "rob-lowe")!)
let quote97 = Quote(quote: "I approach sobriety with the same mentality I approached sports with. You’re going to put in the time. You’ve got to suit up, show up, and keep your eyes on the win.", author: "Molly Bloom", image: UIImage(named: "molly-bloom")!)
let quote98 = Quote(quote: "One day, you’ll tell your story of how you overcame what you went through, and it will be someone else’s survival guide.", author: "Brene Brown", image: UIImage(named: "brene-brown")!)
let quote99 = Quote(quote: "Your best days are ahead of you. The movie starts when the guy gets sober and puts his life back together; it doesn’t end there.", author: "Bucky Sinister", image: UIImage(named: "bucky")!)
let quote100 = Quote(quote: "If you do what you’ve always done, you’ll get what you’ve always gotten.", author: "Tony Robbins", image: UIImage(named: "tony-robbins")!)
let quote101 = Quote(quote: "Breakthroughs don’t get planned, they are prepared for.", author: "Goitsemang Mvula", image: UIImage(named: "goitsemang-mvula")!)
let quote102 = Quote(quote: "When I got sober, I thought giving up was saying goodbye to all the fun and all the sparkle, and it turned out to be just the opposite. That’s when the sparkle started for me.", author: "Mary Karr", image: UIImage(named: "mary-karr")!)
let quote103 = Quote(quote: "If you hear a voice within you say, ‘you cannot paint,’ then by all means paint and that voice will be silenced.", author: "Vincent Van Gogh", image: UIImage(named: "gogh")!)
let quote104 = Quote(quote: "The roots of all goodness lie in the soil of appreciation for goodness.", author: "Dalai Lama", image: UIImage(named: "dalai-lama")!)
let quote105 = Quote(quote: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author: "Albert Einstein", image: UIImage(named: "einstein")!)
let quote106 = Quote(quote: "Nobody stays recovered unless the life they have created is more rewarding and satisfying than the one they left behind.", author: "Anne Fletcher", image: UIImage(named: "anne-fletcher")!)
let quote107 = Quote(quote: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Socrates", image: UIImage(named: "socrates")!)
let quote108 = Quote(quote: "Sometimes the bad things that happen in our lives put us directly on the path to the best things that will ever happen to us.", author: "Nicole Reed", image: UIImage(named: "nicole-reed")!)
let quote109 = Quote(quote: " No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation, he will also provide the way of escape, that you may be able to endure it", author: "Corinthians 10:13", image: UIImage(named: "corinthians")!)
let quote111 = Quote(quote: "If you’re going through hell, keep going.", author: "Winston Churchill", image: UIImage(named: "winston-churchill")!)
let quote112 = Quote(quote: "You have power over your mind—not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", image: UIImage(named: "marcus-aurelius")!)
let quote113 = Quote(quote: "But man is not made for defeat. A man can be destroyed but not defeated.", author: "Ernest Hemingway", image: UIImage(named:"ernest-hemingway")!)
let quote114 = Quote(quote: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt", image: UIImage(named: "fdr")!)
let quote115 = Quote(quote: "Learning never exhausts the mind.", author: "Leonardo da Vinci", image: UIImage(named: "leonardo-vinci")!)
let quote116 = Quote(quote: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson", image: UIImage(named: "thomas-jefferson")!)
let quote117 = Quote(quote: "God Gives His Toughest Battles to His Strongest Soldiers", author: "Isaiah 4:31", image: UIImage(named: "isaiah")!)
let quote118 = Quote(quote: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln", image: UIImage(named: "abraham-lincoln")!)
let quote119 = Quote(quote: "Do not mind anything that anyone tells you about anyone else. Judge everyone and everything for yourself.", author: "Henry James", image: UIImage(named: "henry-james")!)
let quote120 = Quote(quote: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou", image: UIImage(named: "maya-angelou")!)
let quote121 = Quote(quote: "Life is either a daring adventure or nothing.", author: "Helen Keller", image: UIImage(named: "helen-keller")!)
let quote122 = Quote(quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", image: UIImage(named: "henry-thoreau")!)
let quote123 = Quote(quote: "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere.", author: "Barack Obama", image: UIImage(named: "obama2")!)
let quote124 = Quote(quote: "The world is so competitive that if you're stuck on drugs or alcohol, you're not going to be able to compete. It's going to be a disaster. And you know, it potentially can ruin your life.", author: "Donald Trump", image: UIImage(named: "trump")!)
let quote125 = Quote(quote: "Always remember, your focus determines your reality.", author: "George Lucas", image: UIImage(named: "star-wars")!)
let quote126 = Quote(quote: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs", image: UIImage(named: "jobs")!)
let quote127 = Quote(quote: "When you undervalue what you do, the world will undervalue who you are.", author: "Oprah Winfrey", image: UIImage(named: "oprah")!)
let quote128 = Quote(quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", image: UIImage(named: "vidal-sassoon")!)
let quote129 = Quote(quote: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou", image: UIImage(named: "maya-angelou")!)
let quote130 = Quote(quote: "I alone cannot change the world, but I can cast a stone across the water to create many ripples.", author: "Mother Teresa", image: UIImage(named: "mother-teresa")!)
let quote131 = Quote(quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", image: UIImage(named: "confucius")!)
let quote132 = Quote(quote: "Don't find fault, find a remedy: anyone can complain.", author: "Henry Ford", image: UIImage(named: "henry-ford")!)
let quote133 = Quote(quote: "The stories of past courage…can teach, they can offer hope, they can provide inspiration. But they cannot supply courage itself. For this, each man must look into his own soul.", author: "John F. Kennedy", image: UIImage(named: "jfk")!)
let quote134 = Quote(quote: "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.", author: "Buddha", image: UIImage(named: "buddah")!)
let quote135 = Quote(quote: "Knowing what must be done does away with fear.", author: "Rosa Parks", image: UIImage(named: "rosa-parks")!)
let quote136 = Quote(quote: "The two most important days of your life are the day that you’re born and the day that you find out why.", author: "Mark Twain", image: UIImage(named: "mark-twain")!)
let quote137 = Quote(quote: "The test of a first-rate intelligence is the ability to hold two opposed ideas in mind at the same time and still retain the ability to function.", author: "F. Scott Fitzgerald", image: UIImage(named: "fscottf")!)
let quote138 = Quote(quote: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time", author: "Thomas Edison", image: UIImage(named: "thomas-edison")!)
let quote139 = Quote(quote: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale", image: UIImage(named: "florence-nightingale")!)
let quote140 = Quote(quote: "Life shrinks or expands in proportion to one's courage.", author: "Anais Nin", image: UIImage(named: "anais-nin")!)
let quote141 = Quote(quote: "If you don’t risk anything, you risk even more.", author: "Erica Jong", image: UIImage(named: "erica-jong")!)
let quote142 = Quote(quote: "Don’t try to do everything by yourself, but try to connect with people and resources. Having that discipline and perseverance is really important.", author: "Chieu Cao", image: UIImage(named: "chieu-cao")!)
let quote143 = Quote(quote: "There have been so many people who have said to me, ‘You can’t do that,’ but I’ve had an innate belief that they were wrong. Be unwavering and relentless in your approach.", author: "halle berry", image: UIImage(named: "halle-berry")!)
let quote144 = Quote(quote: "If you dont see me on tour, its because I have found happiness away from winning, and that might be the biggest achievement I could ever accomplish.", author: "Andy Irons", image: UIImage(named: "andy-irons")!)
let quote145 = Quote(quote: "May you always remember to enjoy the road, especially when it’s a hard one.", author: "Kobe Bryant", image: UIImage(named: "kobe-bryant")!)
let quote146 = Quote(quote: "I never worry about the problem. I worry about the solution.", author: "Shaquille O'neal", image: UIImage(named: "shaq")!)
let quote157 = Quote(quote: "Freedom of speech and thought matters, especially when it is speech and thought with which we disagree. The moment the majority decides to destroy people for engaging in thought it dislikes, thought crime becomes a reality.", author: "Ben Shapiro", image: UIImage(named: "ben-shapiro")!)
let quote148 = Quote(quote: "It is nice to be around people who think differently than you. They challenge your ideas and keep you from being complacent.", author: "Tucker Carlson", image: UIImage(named: "tucker")!)
let quote149 = Quote(quote: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi", image: UIImage(named: "mahatma-gandhi")!)
let quote110 = Quote(quote: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.", author: "Pele", image: UIImage(named: "pele")!)
let quote150 = Quote(quote: "A man may imagine things that are false, but he can only understand things that are true.", author: "Isaac Newton", image: UIImage(named: "isaac-newton")!)
let quote151 = Quote(quote: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Piccasso", image: UIImage(named: "pablo")!)
let quote152 = Quote(quote: "Aim at heaven and you will get earth thrown in. Aim at earth and you get neither.", author: "C.S. Lewis", image: UIImage(named: "cs-lewis")!)
let quote153 = Quote(quote: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", author: "Romans 12:2", image: UIImage(named: "romans")!)
let quote154 = Quote(quote: "There is only one corner of the universe you can be certain of improving, and that's your own self.", author: "Aldous Huxley", image: UIImage(named: "aldous-huxley")!)
let quote155 = Quote(quote: "Do unto others as you would have them do unto you.", author: "Jesus Christ", image: UIImage(named: "jesus")!)
let quote156 = Quote(quote: "Feeding people half-truths or bullshit to make them feel better (which is almost always about making ourselves feel more comfortable) is unkind.", author: "Brene Brown", image: UIImage(named: "brene-brown")!)
let quote147 = Quote(quote: "Coincidence is God's way of remaining anonymous.", author: "Albert Einstein", image: UIImage(named: "einstein")!)
let quote158 = Quote(quote: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordon", image: UIImage(named: "michael-jordon")!)
let quote159 = Quote(quote: "You’ve been given another day of life. How will you use it? Will you wait until tomorrow as you’ve done for years or decide today is the day you commit to excellence?", author: "Andrew Tate", image: UIImage(named: "andrew-tate")!)
let quote160 = Quote(quote: "Everything that irritates us about others can lead us to an understanding of ourselves.", author: "Carl Jung", image: UIImage(named: "carl-jung")!)
let quote161 = Quote(quote: "It's in responsibility that most people find the meaning that sustains them through life. It's not in happiness. It's not in impulsive pleasure.", author: "Jordon Peterson", image: UIImage(named: "jp")!)
let quote43 = Quote(quote: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh", image: UIImage(named: "gogh")!)
let quote163 = Quote(quote: "Most of us aren't defeated in one decisive battle. We are defeated one tiny, seemingly insignificant surrender at a time that chips away at who we should really be.", author: "Jocko Willink", image: UIImage(named: "jocko")!)
let quote164 = Quote(quote: "The crucial point is: by changing ourselves, we change the world. As we become more loving on the inside, healing occurs on the outside.", author: "David R. Hawkins", image: UIImage(named: "d-hawkins")!)
let quote165 = Quote(quote: "We can only see a short distance ahead, but we can see plenty there that needs to be done.", author: "Alan Turing", image: UIImage(named: "alan-turing")!)
let quote166 = Quote(quote: "The measure of intelligence is the ability to change.", author: "Albert Einstein", image: UIImage(named: "einstein")!)
let quote167 = Quote(quote: "Don’t let rejection create self-doubt. The founder of Starbucks was turned down by 217 of the 242 investors he initially spoke with.", author: "Elizabeth Galbut", image: UIImage(named: "elizabeth-galbut")!)
let quote168 = Quote(quote: "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.", author: "Harriet Tubman", image: UIImage(named: "harriet-tubman")!)
let quote169 = Quote(quote: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill", image: UIImage(named: "winston-churchill")!)
let quote170 = Quote(quote: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean", image: UIImage(named: "jimmy-dean")!)
let quote171 = Quote(quote: "“Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", image: UIImage(named: "mandela")!)
let quote172 = Quote(quote: "Our dilemma is that we hate change and love it at the same time; what we really want is for things to remain the same but get better.", author: "Sydney J. Harris", image: UIImage(named: "sydney-harris")!)
let quote173 = Quote(quote: "Change is the law of life, and those who look only to the past and present are certain to miss the future", author: "John F. Kennedy", image: UIImage(named: "jfk")!)
let quote174 = Quote(quote: "Miracles happen every day, change your perception of what a miracle is and you’ll see them all around you.", author: "Jon Bon Jovi", image: UIImage(named: "bon")!)
let quote175 = Quote(quote: "In order to design a future of positive change, we must first become expert at changing our minds.", author: "Jacque Fresco", image: UIImage(named: "jacque-fresco")!)
let quote176 = Quote(quote: "All of your dreams can come true, if we have the courage to pursue them.", author: "Walt Disney", image: UIImage(named: "walt-disney")!)
let quote177 = Quote(quote: "“My brain is only a receiver, in the Universe there is a core from which we obtain knowledge, strength and inspiration.", author: "Nikola Tesla", image: UIImage(named: "nikola-tesla")!)
let quote178 = Quote(quote: "Freedom (n.): To ask nothing. To expect nothing. To depend on nothing.", author: "Ayn Rand", image: UIImage(named: "ayn-rand")!)
let quote179 = Quote(quote: "There never was a good war or a bad peace.", author: "Benjamin Franklin", image: UIImage(named: "ben-franklin")!)
let quote180 = Quote(quote: "The secret is not to find the meaning of life, but to use your life to make things that are meaningful.", author: "James Clear", image: UIImage(named: "james-clear")!)
let quote181 = Quote(quote: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", author: "Brooker T. Washington", image: UIImage(named: "brooker")!)

let quote182 = Quote(quote: " One, remember to look up at the stars and not down at your feet. Two, never give up work. Work gives you meaning and purpose and life is empty without it. Three, if you are lucky enough to find love, remember it is there and don't throw it away.", author: "Stephen Hawking", image: UIImage(named: "stephen-hawking")!)
let quote183 = Quote(quote: " You cannot teach a man anything; you can only help him discover it in himself.", author: "Galileo", image: UIImage(named: "galileo")!)
let quote184 = Quote(quote: "I am not bound to win, but I am bound to be true. I am not bound to succeed, but I am bound to live by the light that I have. I must stand with anybody that stands right, and stand with him while he is right, and part with him when he goes wrong.", author: "Abraham Lincoln", image: UIImage(named: "abraham-lincoln")!)
let quote185 = Quote(quote: "We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves.", author: "Buddha", image: UIImage(named: "buddah")!)
let quote186 = Quote(quote: "If you don’t fight for what you want, Don’t cry for what you lost.", author: "Krishna", image: UIImage(named: "krishna")!)
let quote187 = Quote(quote: "Life has many ways of testing a person’s will, either by having nothing happen at all or by having everything happen all at once.", author: "Paulo Coelho", image: UIImage(named: "paulo-coelho")!)
let quote88 = Quote(quote: "I've been in a poor physical shape many times in my career and I've had some of my best results. My best performances happened because my mind was in the right place.", author: "Kelly Slater", image: UIImage(named: "kelly-slater")!)
let quote189 = Quote(quote: "My belief is that 'heaven' and 'hell' are metaphorical terms for what you make of your life. In any instant, you have the ability to make your life total pleasure or total hell.", author: "Kelly Slater", image: UIImage(named: "kelly-slater")!)
let quote19 = Quote(quote: "Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.", author: "Arnold Schwarzenegger", image: UIImage(named: "arnold")!)
let quote191 = Quote(quote: "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent.", author: "Arnold Schwarzenegger", image: UIImage(named: "arnold")!)
let quote192 = Quote(quote: "A fool thinks himself to be wise, but a wise man knows himself to be a fool.", author: "William Shakespeare", image: UIImage(named: "shakespeare")!)
let quote27 = Quote(quote: "It is not in the stars to hold our destiny but in ourselves.", author: "William Shakespeare", image: UIImage(named: "shakespeare")!)
let quote194 = Quote(quote: "Every strike brings me closer to the next home run.", author: "Babe Ruth", image: UIImage(named: "babe-ruth")!)
let quote195 = Quote(quote: "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love …", author: "Marcus Aurelias", image: UIImage(named: "marcus-aurelius")!)
let quote196 = Quote(quote: "It always seems impossible until it’s done.", author: "Nelson Mandela", image: UIImage(named: "mandela")!)
let quote197 = Quote(quote: "Man never made any material as resilient as the human spirit.", author: "Bernard Williams", image: UIImage(named: "bernard-williams")!)
let quote198 = Quote(quote: "Happiness is a state of mind that has nothing to do with the external world.", author: "Krishna", image: UIImage(named: "krishna")!)
let quote199 = Quote(quote: "Everyone should consider his body as a priceless gift from one whom he loves above all, a marvelous work of art, of indescribable beauty, and mystery beyond human conception, and so delicate that a word, a breath, a look, nay, a thought may injure it.", author: "Nikola Tesla", image: UIImage(named: "nikola-tesla")!)
let quote200 = Quote(quote: "All the commandments: You shall not commit adultery, you shall not kill, you shall not steal, you shall not covet, and so on, are summed up in this single command: You must love your neighbor as yourself.", author: "Jesus Christ", image: UIImage(named: "jesus")!)
